### ISSUE TITLE
Unaligned memory access

### ISSUE THREAD

**Issue by flowergrass** [AlexAltea/unicorn.js#10]
There is an unaligned memory access within the file unicorn/qemu/include/exec/exec-all.h at line 218.

```C
static inline void tb_set_jmp_target1(uintptr_t jmp_addr, uintptr_t addr)
{
    /* patch the branch destination */
    *(uint32_t *)jmp_addr = addr - (jmp_addr + 4);
    /* no need to flush icache explicitly */
}
```

**Comment by dpgeorge** [comment]
Thanks for the quick turn-around on this issue!

**Comment by AlexAltea** [comment]
@dpgeorge You're welcome. I'm glad you guys are giving Unicorn.js something challenging that finds broken cases I missed while porting it.

PS: I really like the idea of MicroPython. Hats off. :-)

**Comment by dpgeorge** [comment]
> I'm glad you guys are giving Unicorn.js something challenging

Well this is just the beginning... if unicorn.js can work flawlessly (to the same level as the C version) then we have a whole lot of cool stuff to throw at it :)
