### ISSUE TITLE
ARM64 registers are repeated in unicorn_constants.js

### ISSUE THREAD

**Issue by qwergle** [AlexAltea/unicorn.js#33]
A little background: Currently, I'm trying to write (at least some of) the documentation for the constants. From reading `unicorn_constants.js` before, I know that there are three parts to it: register constants, X86 instruction constants, and Unicorn engine constants. So, I decide to use Control-F to find each register and create a placeholder. I find that at the very end, the list of ARM64 registers (the list at the _very beginning of the file_) is repeated at the end. I realize that it's auto-generated and that it says explicitly not to edit it, but it should be edited to remove this redundancy.

**Comment by AlexAltea** [comment]
Nice catch, seems like the [last line effect](https://pvs-studio.com/en/blog/posts/cpp/0260/) strikes again! 😄

Fixed at https://github.com/AlexAltea/unicorn.js/commit/6e998393d863a37659c09046d4835003e6554a35

**Comment by AlexAltea** [comment]
Just to clarify, `build.py` was at fault here.

**Comment by qwergle** [comment]
> Just to clarify, `build.py` was at fault here.

I thought so. After all, it was made by `build.py`.
