### ISSUE TITLE
Is it possible to put all release files into dist folder?

### ISSUE THREAD

**Issue by PeterDaveHello** [AlexAltea/unicorn.js#9]
Hi @AlexAltea! I'm Peter from @cdnjs, as unicorn.js is awesome, we are hosting it here: https://cdnjs.com/libraries/unicorn.js, I just have a small question about the release file, I saw 4 released files in the `dist` here: https://github.com/AlexAltea/unicorn.js/tree/v1.0/dist, but there seems to be more in the release page: https://github.com/AlexAltea/unicorn.js/releases/tag/v1.0, uploaded manually, is it possible to add all of them in the future releases? (Just in the tagged commit) So that we can automatically pick up all the future releases, thank you!

**Comment by AlexAltea** [comment]
Sure. I thought @cdnjs was fetching the files from the release pages, so my .gitignore file was filtering out the Unicorn.js variants not needed for the GitHub Pages demos.
Fixed on cf56268280cc31055fbe5d7ddc750b9d24ffa825.

**Comment by PeterDaveHello** [comment]
Thanks @AlexAltea
